name: CI

on:
  push:
    branches:
      - main

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set GITHUB_SHA_SHORT
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Image
        run: |
          make build
          docker tag \
            go-statsd-example:latest\
            ghcr.io/jsirianni/go-statsd-example:${GITHUB_SHA_SHORT}

      - name: Docker Push
        run: "docker push ghcr.io/jsirianni/go-statsd-example:${GITHUB_SHA_SHORT}"
